# Generated by Django 5.1.3 on 2025-01-26 07:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('name', models.CharField(default='Unnamed Route', max_length=255, unique=True)),
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Stop', max_length=255, unique=True)),
                ('is_institute', models.BooleanField(default=False)),
                ('is_valuationcamp', models.BooleanField(default=False)),
                ('is_intermediate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RouteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('mode', models.CharField(choices=[('Taxi', 'Taxi'), ('Train', 'Train'), ('Bus', 'Bus'), ('Walk', 'Walk'), ('Not Selected', 'Not Selected')], default='Not Selected', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='ta.route')),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_end', to='ta.routestop')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_start', to='ta.routestop')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_routes', to='ta.routestop'),
        ),
        migrations.AddField(
            model_name='route',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_routes', to='ta.routestop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(blank=True, related_name='routes', to='ta.routestop'),
        ),
        migrations.CreateModel(
            name='RoutePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths', to='ta.route')),
                ('route_links', models.ManyToManyField(related_name='paths', to='ta.routelink')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_destination', to='ta.routestop')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_source', to='ta.routestop')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('route', 'source', 'destination', 'order'), name='unique_route_path')],
            },
        ),
    ]
