# Generated by Django 5.1.3 on 2025-01-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(default='Unnamed Route', max_length=255),
        ),
    ]
