# Generated by Django 4.2.18 on 2025-01-31 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0002_alter_route_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={},
        ),
        migrations.AlterModelOptions(
            name='routepath',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='routepath',
            name='unique_route_path',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='routestop',
            old_name='is_institute',
            new_name='isInstitute',
        ),
        migrations.RenameField(
            model_name='routestop',
            old_name='is_intermediate',
            new_name='isIntermediateStop',
        ),
        migrations.RenameField(
            model_name='routestop',
            old_name='is_valuationcamp',
            new_name='isValuationCamp',
        ),
        migrations.RemoveField(
            model_name='route',
            name='name',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='stops',
        ),
        migrations.RemoveField(
            model_name='routepath',
            name='route_links',
        ),
        migrations.AddField(
            model_name='route',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routeDestination', to='ta.routestop'),
        ),
        migrations.AlterField(
            model_name='route',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routeSource', to='ta.routestop'),
        ),
        migrations.AlterField(
            model_name='routelink',
            name='end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routeLinkEnd', to='ta.routestop'),
        ),
        migrations.AlterField(
            model_name='routelink',
            name='mode',
            field=models.CharField(choices=[('Taxi', 'Taxi'), ('Train', 'Train'), ('Bus', 'Bus'), ('Walk', 'Walk'), ('Not Selected', 'Not Selected')], default='Not Selected', max_length=20),
        ),
        migrations.AlterField(
            model_name='routelink',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta.route'),
        ),
        migrations.AlterField(
            model_name='routelink',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routeLinkStart', to='ta.routestop'),
        ),
        migrations.AlterField(
            model_name='routepath',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routePathDestination', to='ta.routestop'),
        ),
        migrations.AlterField(
            model_name='routepath',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='routepath',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta.route'),
        ),
        migrations.AlterField(
            model_name='routepath',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routePathSource', to='ta.routestop'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
