# Generated by Django 4.2.18 on 2025-02-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0003_alter_route_options_alter_routepath_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routestop',
            name='isInstitute',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='isIntermediateStop',
        ),
        migrations.RemoveField(
            model_name='routestop',
            name='isValuationCamp',
        ),
        migrations.AddField(
            model_name='routestop',
            name='stopType',
            field=models.CharField(choices=[('IntermediateStop', 'IntermediateStop'), ('Insititute', 'Insititute'), ('ValuationCamp', 'ValuationCamp')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routelink',
            name='mode',
            field=models.CharField(choices=[('Taxi', 'Taxi'), ('Train', 'Train'), ('Bus', 'Bus'), ('Walk', 'Walk')], max_length=20),
        ),
    ]
