# Generated by Django 4.2.18 on 2025-02-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0006_alter_routestop_stoptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routelink',
            name='mode',
            field=models.IntegerField(choices=[('1', 'Taxi'), ('2', 'Train'), ('3', 'Bus'), ('4', 'Walk')]),
        ),
        migrations.CreateModel(
            name='TemporaryRouteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('mode', models.IntegerField(choices=[('1', 'Taxi'), ('2', 'Train'), ('3', 'Bus'), ('4', 'Walk')])),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporaryRouteLinkEnd', to='ta.routestop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta.route')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporaryRouteLinkStart', to='ta.routestop')),
            ],
        ),
    ]
