# Generated by Django 4.2.18 on 2025-02-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ta', '0007_alter_routelink_mode_temporaryroutelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='routelink',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temporaryroutelink',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routelink',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Taxi'), (2, 'Train'), (3, 'Bus'), (4, 'Walk')]),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='stopType',
            field=models.IntegerField(choices=[(1, 'Intermediate Stop'), (2, 'Institute'), (3, 'Valuation Camp')]),
        ),
        migrations.AlterField(
            model_name='temporaryroutelink',
            name='mode',
            field=models.IntegerField(choices=[(1, 'Taxi'), (2, 'Train'), (3, 'Bus'), (4, 'Walk')]),
        ),
        migrations.DeleteModel(
            name='RoutePath',
        ),
    ]
